eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/
server:
  port: 8004
spring:
  application:
    name: service-ribbon
  boot:
    admin:
      client:
        url: "http://localhost:9997"
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS