eureka:
  client:
    serviceUrl:
      # 注明自己的服务注册中心的地址
      defaultZone: http://localhost:7777/eureka/
server:
  port: 9998
spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      #dev开发环境配置文件,test测试环境,pro正式环境
      profile: dev
      uri: http://localhost:9999/
      discovery:
        #从配置中心读取文件
        enabled: true
        # 配置中心的serviceId，即服务名
        service-id: config-server
